In [32]:
import pandas as pd

In [33]:
df=pd.read_csv("C:/Users/Lenovo/Desktop/House_Rent_Analysis/Dataset/June_8_data_metro_closest_stations.csv")

In [34]:
df.head()

,Unnamed: 0,size_sq_ft,propertyType,bedrooms,latitude,longitude,suburbName,cityName,price,companyName,closest_mtero_station_km,AP_dist_km,Aiims_dist_km,NDRLW_dist_km
0,0,400,Independent Floor,1,28.641010,77.284386,East Delhi,Delhi,9000,Dream Homez,0.577495,21.741188,11.119239,6.227231
1,1,1050,Apartment,2,28.594969,77.298668,East Delhi,Delhi,20000,Rupak Properties Stock,0.417142,21.401856,9.419061,9.217502
2,2,2250,Independent Floor,2,28.641806,77.293922,East Delhi,Delhi,28000,Aashiyana Real Estate,0.125136,22.620365,11.829486,7.159184
3,3,1350,Independent Floor,2,28.644363,77.293228,East Delhi,Delhi,28000,Shivam Real Estate,0.371709,22.681201,11.982708,7.097348
4,4,450,Apartment,2,28.594736,77.311150,East Delhi,Delhi,12500,Shree Properties,1.087760,22.592810,10.571573,10.263271

In [35]:
df.columns

Index(['Unnamed: 0', 'size_sq_ft', 'propertyType', 'bedrooms', 'latitude',
       'longitude', 'suburbName', 'cityName', 'price', 'companyName',
       'closest_mtero_station_km', 'AP_dist_km', 'Aiims_dist_km',
       'NDRLW_dist_km'],
      dtype='object')

In [36]:
df.rename(columns = {'Unnamed: 0':'IndexNo'}, inplace = True)

In [37]:
df.head()

,IndexNo,size_sq_ft,propertyType,bedrooms,latitude,longitude,suburbName,cityName,price,companyName,closest_mtero_station_km,AP_dist_km,Aiims_dist_km,NDRLW_dist_km
0,0,400,Independent Floor,1,28.641010,77.284386,East Delhi,Delhi,9000,Dream Homez,0.577495,21.741188,11.119239,6.227231
1,1,1050,Apartment,2,28.594969,77.298668,East Delhi,Delhi,20000,Rupak Properties Stock,0.417142,21.401856,9.419061,9.217502
2,2,2250,Independent Floor,2,28.641806,77.293922,East Delhi,Delhi,28000,Aashiyana Real Estate,0.125136,22.620365,11.829486,7.159184
3,3,1350,Independent Floor,2,28.644363,77.293228,East Delhi,Delhi,28000,Shivam Real Estate,0.371709,22.681201,11.982708,7.097348
4,4,450,Apartment,2,28.594736,77.311150,East Delhi,Delhi,12500,Shree Properties,1.087760,22.592810,10.571573,10.263271

In [38]:
df.describe()

,IndexNo,size_sq_ft,bedrooms,latitude,longitude,price,closest_mtero_station_km,AP_dist_km,Aiims_dist_km,NDRLW_dist_km
count,17890.000000,17890.000000,17890.000000,17890.000000,17890.000000,1.789000e+04,17890.000000,17890.000000,17890.000000,17890.000000
mean,8944.500000,1176.342091,2.168865,28.609382,77.168368,3.345196e+04,0.931495,13.727784,11.238134,11.421994
std,5164.542493,873.751044,0.971414,0.099547,0.097611,8.802054e+04,8.287856,11.357063,11.167202,11.063323
min,0.000000,100.000000,1.000000,19.185120,73.213829,1.200000e+03,0.000692,1.784779,0.634508,0.722023
25%,4472.250000,620.000000,1.000000,28.562540,77.103718,1.350000e+04,0.457782,11.018715,7.769267,7.986813
50%,8944.500000,900.000000,2.000000,28.611803,77.168755,2.200000e+04,0.698560,13.184035,10.515524,11.015571
75%,13416.750000,1600.000000,3.000000,28.651593,77.224998,3.500000e+04,1.087740,17.163502,15.514042,15.192483
max,17889.000000,16521.000000,15.000000,28.872597,80.358467,5.885646e+06,1096.479453,1109.894053,1115.621439,1123.778457

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17890 entries, 0 to 17889
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   IndexNo                   17890 non-null  int64
 1   size_sq_ft                17890 non-null  int64
 2   propertyType              17890 non-null  object
 3   bedrooms                  17890 non-null  int64
 4   latitude                  17890 non-null  float64
 5   longitude                 17890 non-null  float64
 6   suburbName                17890 non-null  object
 7   cityName                  17890 non-null  object
 8   price                     17890 non-null  int64
 9   companyName               17890 non-null  object
 10  closest_mtero_station_km  17890 non-null  float64
 11  AP_dist_km                17890 non-null  float64
 12  Aiims_dist_km             17890 non-null  float64
 13  NDRLW_dist_km             17890 non-null  float64
dtypes: float64(6), int64(4), object(4)
memory usage: 1.9+ MB

In [40]:
df.isna().sum()

IndexNo                     0
size_sq_ft                  0
propertyType                0
bedrooms                    0
latitude                    0
longitude                   0
suburbName                  0
cityName                    0
price                       0
companyName                 0
closest_mtero_station_km    0
AP_dist_km                  0
Aiims_dist_km               0
NDRLW_dist_km               0
dtype: int64

In [41]:
df.isnull().sum()

IndexNo                     0
size_sq_ft                  0
propertyType                0
bedrooms                    0
latitude                    0
longitude                   0
suburbName                  0
cityName                    0
price                       0
companyName                 0
closest_mtero_station_km    0
AP_dist_km                  0
Aiims_dist_km               0
NDRLW_dist_km               0
dtype: int64

In [42]:
df['companyName'].value_counts()

Gurmeet                668
Sky Properties         384
Jagdamba Associates    307
dwarka property        243
Arora Associates       243
                      ...
BHAGAT SINGH NEGI        1
Simmy Gupta              1
Divya                    1
shalini                  1
ANIL KUMAR BAREJA        1
Name: companyName, Length: 1387, dtype: int64

In [43]:
df['companyName'].unique()

array(['Dream Homez', 'Rupak Properties Stock', 'Aashiyana Real Estate',
       ..., 'K K LAVANIA', 'sanjeev', 'ANIL KUMAR BAREJA'], dtype=object)

In [44]:
df['companyName'].nunique()

1387

In [45]:
df['companyName']=df.companyName.str.replace('A to Z Property','A_to_Z_Property').str.replace('A 2 Z Property','A_to_Z_Property').str.replace('A to z realty','A_to_Z_Property')

In [46]:
df['companyName'].value_counts()

Gurmeet                668
Sky Properties         384
Jagdamba Associates    307
dwarka property        243
Arora Associates       243
                      ...
Raj Kumar                1
kunal                    1
Savita chhabra           1
RAJAN                    1
ANIL KUMAR BAREJA        1
Name: companyName, Length: 1385, dtype: int64

In [47]:
company_names=df['companyName'].values.tolist()

In [48]:
type(company_names)

list

In [49]:
len(company_names)

17890

In [50]:
unique_company_names=[]
for name in company_names:
    if name not in unique_company_names:
        unique_company_names.append(name)

In [51]:
len(unique_company_names)

1385

In [52]:
for i in range(0,len(company_names)-1):
    if company_names.count(company_names[i]) < 50:
        company_names[i]='Others'

In [53]:
company_names

['Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Others',
 'Golden Properties',
 'Welcome Properties',
 'Akash Properties',
 'Shivam Properties',
 'Others',
 'Tanya Associates',
 'BK Associates',
 'Hans Properties',
 'Aaditya properties',
 'Prince Associates',
 'Others',
 'Arora Properties',
 'Aradhya Properties',
 'Others',
 'Others',
 'Others',
 'Delli Property',
 'Others',
 'Golden Properties',
 'Shivam Real Estate',
 'Welcome Properties',
 'Others',
 'Shivam Properties',
 'Akash Properties',
 'BK Associates',
 'Others',
 'Others',
 'Others',
 'Prince Associates',
 'Arora Properties',
 'Others',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Shivam Properties',
 'Golden Properties',
 'BK Associates',
 'Prince Associates',
 'Welcome Properties',
 'Akash Properties',
 'Arora Properties',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Others',
 'Shivam Properties',
 'Others',
 'Akash Properties',
 'BK Associates',
 'Prince Associates',
 'Golden Properties',
 'Welcome Properties',
 'Arora Properties',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Prince Associates',
 'Shivam Properties',
 'Arora Properties',
 'Akash Properties',
 'BK Associates',
 'Welcome Properties',
 'Golden Properties',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Others',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Others',
 'Shivam Real Estate',
 'Shivam Real Estate',
 'Welcome Properties',
 'Welcome Properties',
 'Welcome Properties',
 'Akash Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'BK Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Golden Properties',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'BK Associates',
 'BK Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Arora Properties',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'Arora Properties',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Arora Properties',
 'Shivam Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Prince Associates',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Arora Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Shivam Properties',
 'Golden Properties',
 'Prince Associates',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Shivam Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Golden Properties',
 'Prince Associates',
 'Prince Associates',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Welcome Properties',
 'Welcome Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Arora Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Akash Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Others',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Aradhya Properties',
 'Others',
 'Others',
 'Others',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'BK Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'ASAssociates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Others',
 'ASAssociates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Rana Associates',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'ASAssociates',
 'ASAssociates',
 'Nestaway',
 'Others',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'Nestaway',
 'ASAssociates',
 'ASAssociates',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'Nestaway',
 'Nestaway',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'Nestaway',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'Nestaway',
 'Nestaway',
 'Nestaway',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'ASAssociates',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Nestaway',
 'Others',
 'Nestaway',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'Others',
 'Others',
 'BK Associates',
 'Others',
 'Others',
 'Others',
 'ASAssociates',
 'Others',
 'Others',
 'Others',
 'Others',
 'BK Associates',
 'Others',
 'Others',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'Others',
 'Mass Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'Others',
 'Others',
 'Others',
 'Mass Properties',
 'Others',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'sk roy',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'Mass Properties',
 'BK Associates',
 'Others',
 'Others',
 'Delli Property',
 'Others',
 'Others',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Delli Property',
 'Others',
 'Others',
 'Others',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'ASAssociates',
 'Others',
 'Mass Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'sk roy',
 'Mass Properties',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'BK Associates',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'Others',
 'vajpayee properties',
 'vajpayee properties',
 'vajpayee properties',
 ...]

In [54]:
new_company_names= pd.DataFrame(company_names)

In [55]:
type(new_company_names)

pandas.core.frame.DataFrame

In [56]:
df['companyName']=new_company_names

In [57]:
df['companyName']

0                    Others
1                    Others
2                    Others
3        Shivam Real Estate
4                    Others
                ...
17885                Others
17886                Others
17887                Others
17888                Others
17889               sanjeev
Name: companyName, Length: 17890, dtype: object

In [58]:
df['companyName'].value_counts()

Others                           6517
Gurmeet                           668
Sky Properties                    384
Jagdamba Associates               307
dwarka property                   243
                                 ...
Welcome Properties                 52
Mass Properties                    51
Ambika Properties                  51
Shubham Estates / Shubhbhoomi      50
sanjeev                             1
Name: companyName, Length: 114, dtype: int64

In [59]:
df['companyName'].unique()

array(['Others', 'Shivam Real Estate', 'Golden Properties',
       'Welcome Properties', 'Akash Properties', 'Shivam Properties',
       'Tanya Associates', 'BK Associates', 'Hans Properties',
       'Aaditya properties', 'Prince Associates', 'Arora Properties',
       'Aradhya Properties', 'Delli Property', 'Rana Associates',
       'ASAssociates', 'Nestaway', 'Mass Properties', 'sk roy',
       'vajpayee properties', 'golden properties', 'DKS Realty Homes',
       'A_to_Z_Property', 'user', 'SkyLark Properties',
       'Shiv Shakti Properties Consultant Builders', 'VR Property',
       'B M Associates', 'Sethi Properties', 'Jagdamba Associates',
       'dwarka property', 'Bm properties', 'Shivansh Associate',
       'Batra Associates', 'Atul Kumar', 'Guru kipra properties',
       'Baghla Estates', 'Deepak Verma', 'Property Hub', 'Realty Centre',
       'New golden properties', 'K Homes', 'NCR Investors',
       'Delhi dreams properties consultant', 'Gorakh property',
       'Namberdaar Properties', 'Arora Associates', 'India Homes',
       'Moneytree real estate consultants', 'HR Associates',
       'vsr builder pvt ltd', 'A R Realtors', 'M V Properties',
       'Mohan Associates', 'The Perfect Estates', 'Navigators Estate',
       'Dinesh associates', 'Hari Om Group', 'Sameer Property',
       'Prateek Property', 'Dagar Co', 'Tiwari Properties',
       'Angel Property Services', 'Dream Home', 'Property Clinic',
       'Vineet Properties', 'Friends Property', 'Aarti properties',
       'Ganeshji Property', 'Shubham Estates / Shubhbhoomi',
       'BUNIYAAD ESTATE', 'Rudransh Associates', 'Shree bala ji',
       'Gohri Associates', 'Ambika Properties', 'Vishal',
       'RG Real Estates', 'Mantu Properties', 'Makan Properties',
       'Vohra Associated', 'Ajay Properties',
       'PRANAV MENDIRATTA REALTORS', 'Rai Properties',
       'Hites Properties And Construction', 'Sarita Properties',
       'arun thakur', 'maheshwari Properties', 'KC Real Estate',
       'BM PROPERTIES', 'Gurmeet',
       'K P Properties and Finance Consultant', 'Sky Properties',
       'Tera properties', 'Sharma Properties', 'RVS properties',
       'Malhotra Properties', 'Vijay Estate', 'Anand Associated',
       'Sanjay Properties', 'Yk Gupta Associates', 'Pearl Estates',
       'Jupiter Property Consultant', 'truelink investor solution',
       'RAJENDRA ASSOCIATES', 'KALHAN REALTORS PVT LTD',
       'Bajrang Garg Properties and Developers', 'Grand Realty',
       'Behl Properties', 'Hemkunt Properties', 'New Hemkunt Properties',
       'KB Associates', 'inter link estates', 'Dhan Laxmi Properties',
       'sanjeev'], dtype=object)

In [61]:
df.to_csv("new_house_data.csv",index=False)

In [62]:
new_df=pd.read_csv("new_house_data.csv")

In [63]:
new_df.head()

,IndexNo,size_sq_ft,propertyType,bedrooms,latitude,longitude,suburbName,cityName,price,companyName,closest_mtero_station_km,AP_dist_km,Aiims_dist_km,NDRLW_dist_km
0,0,400,Independent Floor,1,28.641010,77.284386,East Delhi,Delhi,9000,Others,0.577495,21.741188,11.119239,6.227231
1,1,1050,Apartment,2,28.594969,77.298668,East Delhi,Delhi,20000,Others,0.417142,21.401856,9.419061,9.217502
2,2,2250,Independent Floor,2,28.641806,77.293922,East Delhi,Delhi,28000,Others,0.125136,22.620365,11.829486,7.159184
3,3,1350,Independent Floor,2,28.644363,77.293228,East Delhi,Delhi,28000,Shivam Real Estate,0.371709,22.681201,11.982708,7.097348
4,4,450,Apartment,2,28.594736,77.311150,East Delhi,Delhi,12500,Others,1.087760,22.592810,10.571573,10.263271